# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("*{\n"
"    color: rgb(238, 238, 236);\n"
"    border: none;\n"
"}\n"
"#mainBodySubContainer{\n"
"    background-color: rgb(3, 33, 77);\n"
"}\n"
"QPushButton{\n"
"    padding: 3px 3px;\n"
"    border-radius: 10px;\n"
"}\n"
"#widget_5{\n"
"border-image: url(:/icons/icons/SimboloPcDrones.svg);\n"
"}\n"
"#widget_4{\n"
"border-image: url(:/icons/icons/SimboloPcDrones.svg);\n"
"}\n"
"#widget_3{\n"
"border-image: url(:/icons/icons/SimboloPcDrones.svg);\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_30.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainWindowWidget = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWindowWidget.sizePolicy().hasHeightForWidth())
        self.mainWindowWidget.setSizePolicy(sizePolicy)
        self.mainWindowWidget.setStyleSheet("")
        self.mainWindowWidget.setObjectName("mainWindowWidget")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.mainWindowWidget)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.mainSubWindow = QtWidgets.QWidget(self.mainWindowWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainSubWindow.sizePolicy().hasHeightForWidth())
        self.mainSubWindow.setSizePolicy(sizePolicy)
        self.mainSubWindow.setStyleSheet("")
        self.mainSubWindow.setObjectName("mainSubWindow")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainSubWindow)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topMenuContainer = QtWidgets.QWidget(self.mainSubWindow)
        self.topMenuContainer.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.topMenuContainer.setObjectName("topMenuContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topMenuContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topMenuSubContainer = QtWidgets.QWidget(self.topMenuContainer)
        self.topMenuSubContainer.setStyleSheet("")
        self.topMenuSubContainer.setObjectName("topMenuSubContainer")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.topMenuSubContainer)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.frame_2 = QtWidgets.QFrame(self.topMenuSubContainer)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.min = QtWidgets.QPushButton(self.frame_2)
        self.min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/basic/icons/feather/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min.setIcon(icon)
        self.min.setIconSize(QtCore.QSize(20, 20))
        self.min.setObjectName("min")
        self.horizontalLayout_3.addWidget(self.min)
        self.max = QtWidgets.QPushButton(self.frame_2)
        self.max.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/basic/icons/feather/maximize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max.setIcon(icon1)
        self.max.setIconSize(QtCore.QSize(20, 20))
        self.max.setObjectName("max")
        self.horizontalLayout_3.addWidget(self.max)
        self.close = QtWidgets.QPushButton(self.frame_2)
        self.close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/basic/icons/feather/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon2)
        self.close.setIconSize(QtCore.QSize(20, 20))
        self.close.setObjectName("close")
        self.horizontalLayout_3.addWidget(self.close)
        self.verticalLayout_34.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.frame_3 = QtWidgets.QFrame(self.topMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainButtonsFrame = QtWidgets.QFrame(self.frame_3)
        self.mainButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainButtonsFrame.setObjectName("mainButtonsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainButtonsFrame)
        self.horizontalLayout_2.setContentsMargins(9, 0, 0, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.homeBtn = QtWidgets.QPushButton(self.mainButtonsFrame)
        self.homeBtn.setStyleSheet("background-color: rgb(3, 33, 77);")
        self.homeBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/IconoHomeGris.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon3)
        self.homeBtn.setIconSize(QtCore.QSize(48, 48))
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_2.addWidget(self.homeBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.mainButtonsFrame)
        self.settingsBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/IconoConfiAzul.png.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/IconoConfiGris.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.settingsBtn.setIcon(icon4)
        self.settingsBtn.setIconSize(QtCore.QSize(48, 48))
        self.settingsBtn.setObjectName("settingsBtn")
        self.horizontalLayout_2.addWidget(self.settingsBtn)
        self.missionBtn = QtWidgets.QPushButton(self.mainButtonsFrame)
        self.missionBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/IconoMisionAzul.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.missionBtn.setIcon(icon5)
        self.missionBtn.setIconSize(QtCore.QSize(48, 48))
        self.missionBtn.setObjectName("missionBtn")
        self.horizontalLayout_2.addWidget(self.missionBtn)
        self.reportBtn = QtWidgets.QPushButton(self.mainButtonsFrame)
        self.reportBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/IconoReporteAzul.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reportBtn.setIcon(icon6)
        self.reportBtn.setIconSize(QtCore.QSize(48, 48))
        self.reportBtn.setObjectName("reportBtn")
        self.horizontalLayout_2.addWidget(self.reportBtn)
        self.horizontalLayout.addWidget(self.mainButtonsFrame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Univalle = QtWidgets.QLabel(self.frame_8)
        self.Univalle.setMaximumSize(QtCore.QSize(37, 48))
        self.Univalle.setText("")
        self.Univalle.setPixmap(QtGui.QPixmap(":/icons/icons/Univalle.svg"))
        self.Univalle.setScaledContents(True)
        self.Univalle.setObjectName("Univalle")
        self.horizontalLayout_4.addWidget(self.Univalle)
        self.MasterDrones = QtWidgets.QLabel(self.frame_8)
        self.MasterDrones.setMaximumSize(QtCore.QSize(230, 48))
        self.MasterDrones.setText("")
        self.MasterDrones.setPixmap(QtGui.QPixmap(":/icons/icons/MasterDrones.svg"))
        self.MasterDrones.setScaledContents(True)
        self.MasterDrones.setObjectName("MasterDrones")
        self.horizontalLayout_4.addWidget(self.MasterDrones)
        self.horizontalLayout.addWidget(self.frame_8, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.logoLabelFrame = QtWidgets.QFrame(self.frame_3)
        self.logoLabelFrame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.logoLabelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoLabelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoLabelFrame.setObjectName("logoLabelFrame")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.logoLabelFrame)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.PSI = QtWidgets.QLabel(self.logoLabelFrame)
        self.PSI.setMaximumSize(QtCore.QSize(110, 48))
        self.PSI.setText("")
        self.PSI.setPixmap(QtGui.QPixmap(":/icons/icons/PSI.svg"))
        self.PSI.setScaledContents(True)
        self.PSI.setObjectName("PSI")
        self.horizontalLayout_31.addWidget(self.PSI)
        self.userBtn_2 = QtWidgets.QPushButton(self.logoLabelFrame)
        self.userBtn_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/userAzul.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.userBtn_2.setIcon(icon7)
        self.userBtn_2.setIconSize(QtCore.QSize(48, 48))
        self.userBtn_2.setObjectName("userBtn_2")
        self.horizontalLayout_31.addWidget(self.userBtn_2)
        self.horizontalLayout.addWidget(self.logoLabelFrame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_34.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.topMenuSubContainer, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.topMenuContainer, 0, QtCore.Qt.AlignTop)
        self.mainBodyContainer = QtWidgets.QWidget(self.mainSubWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainBodySubContainer = QtWidgets.QWidget(self.mainBodyContainer)
        self.mainBodySubContainer.setObjectName("mainBodySubContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.mainBodySubContainer)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.switchPagesStacked = QtWidgets.QStackedWidget(self.mainBodySubContainer)
        self.switchPagesStacked.setStyleSheet("background-color: rgb(3, 33, 77);")
        self.switchPagesStacked.setObjectName("switchPagesStacked")
        self.homePage_3 = QtWidgets.QWidget()
        self.homePage_3.setObjectName("homePage_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.homePage_3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_13 = QtWidgets.QWidget(self.homePage_3)
        self.widget_13.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label = QtWidgets.QLabel(self.frame_13)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.verticalLayout_33.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_9.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_18.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_10.setStyleSheet("background-color: rgb(206, 92, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_18.addWidget(self.pushButton_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/batteryVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon8)
        self.pushButton_11.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_18.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/gpsVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon9)
        self.pushButton_12.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_18.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/motorVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon10)
        self.pushButton_13.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_18.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/cpuVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon11)
        self.pushButton_14.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_18.addWidget(self.pushButton_14)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_16.setStyleSheet("")
        self.pushButton_16.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/imuVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon12)
        self.pushButton_16.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_18.addWidget(self.pushButton_16)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/cameraVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon13)
        self.pushButton_15.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_18.addWidget(self.pushButton_15)
        self.verticalLayout_33.addWidget(self.frame_14)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_33.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_21.addWidget(self.pushButton_33)
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_34.setStyleSheet("background-color: rgb(206, 92, 0);")
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_21.addWidget(self.pushButton_34)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_35.setStyleSheet("")
        self.pushButton_35.setText("")
        self.pushButton_35.setIcon(icon8)
        self.pushButton_35.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_21.addWidget(self.pushButton_35)
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_36.setStyleSheet("")
        self.pushButton_36.setText("")
        self.pushButton_36.setIcon(icon9)
        self.pushButton_36.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_36.setObjectName("pushButton_36")
        self.horizontalLayout_21.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_37.setStyleSheet("")
        self.pushButton_37.setText("")
        self.pushButton_37.setIcon(icon10)
        self.pushButton_37.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_21.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_38.setStyleSheet("")
        self.pushButton_38.setText("")
        self.pushButton_38.setIcon(icon11)
        self.pushButton_38.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_38.setObjectName("pushButton_38")
        self.horizontalLayout_21.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_39.setStyleSheet("")
        self.pushButton_39.setText("")
        self.pushButton_39.setIcon(icon12)
        self.pushButton_39.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_39.setObjectName("pushButton_39")
        self.horizontalLayout_21.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_40.setStyleSheet("")
        self.pushButton_40.setText("")
        self.pushButton_40.setIcon(icon13)
        self.pushButton_40.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_40.setObjectName("pushButton_40")
        self.horizontalLayout_21.addWidget(self.pushButton_40)
        self.verticalLayout_33.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        self.frame_17.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pushButton_41 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_41.setStyleSheet("background-color: rgb(52, 101, 164);")
        self.pushButton_41.setObjectName("pushButton_41")
        self.horizontalLayout_22.addWidget(self.pushButton_41)
        self.pushButton_42 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_42.setStyleSheet("background-color: rgb(206, 92, 0);")
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_22.addWidget(self.pushButton_42)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem2)
        self.pushButton_43 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_43.setStyleSheet("")
        self.pushButton_43.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/batteryVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/batteryRojo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_43.setIcon(icon14)
        self.pushButton_43.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_22.addWidget(self.pushButton_43)
        self.pushButton_44 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_44.setStyleSheet("")
        self.pushButton_44.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/gpsVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/gpsRojo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_44.setIcon(icon15)
        self.pushButton_44.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_22.addWidget(self.pushButton_44)
        self.pushButton_45 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_45.setStyleSheet("")
        self.pushButton_45.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/motorVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/motorRojo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_45.setIcon(icon16)
        self.pushButton_45.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_22.addWidget(self.pushButton_45)
        self.pushButton_46 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_46.setStyleSheet("")
        self.pushButton_46.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/cpuVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/cpuRojo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_46.setIcon(icon17)
        self.pushButton_46.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_22.addWidget(self.pushButton_46)
        self.pushButton_47 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_47.setStyleSheet("")
        self.pushButton_47.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/imuVerde.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/imuRojo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_47.setIcon(icon18)
        self.pushButton_47.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_22.addWidget(self.pushButton_47)
        self.pushButton_48 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_48.setStyleSheet("")
        self.pushButton_48.setText("")
        self.pushButton_48.setIcon(icon13)
        self.pushButton_48.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout_22.addWidget(self.pushButton_48)
        self.verticalLayout_33.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_13)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_33.addWidget(self.frame_18)
        self.horizontalLayout_9.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.widget_13)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_7.setStyleSheet("background-color: rgb(3, 33, 77);")
        self.pushButton_7.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/connectionGris.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon19)
        self.pushButton_7.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_32.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_8.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/telemetryAzul.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon20)
        self.pushButton_8.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_32.addWidget(self.pushButton_8)
        self.horizontalLayout_9.addWidget(self.frame_12, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.horizontalLayout_8.addWidget(self.widget_13)
        self.switchPagesStacked.addWidget(self.homePage_3)
        self.ConfiPage = QtWidgets.QWidget()
        self.ConfiPage.setObjectName("ConfiPage")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ConfiPage)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_6 = QtWidgets.QWidget(self.ConfiPage)
        self.widget_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_6.setStyleSheet("")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.widget_15 = QtWidgets.QWidget(self.widget_6)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setSpacing(0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.frame_26 = QtWidgets.QFrame(self.widget_15)
        self.frame_26.setStyleSheet("")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_11 = QtWidgets.QLabel(self.frame_26)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_19.addWidget(self.label_11)
        self.verticalLayout_46.addWidget(self.frame_26, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_19 = QtWidgets.QFrame(self.widget_15)
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.widget_30 = QtWidgets.QWidget(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_30.sizePolicy().hasHeightForWidth())
        self.widget_30.setSizePolicy(sizePolicy)
        self.widget_30.setMaximumSize(QtCore.QSize(300, 370))
        self.widget_30.setStyleSheet("background-color: rgb(203, 218, 216);\n"
"padding: 3px 3px;\n"
"border-radius: 10px;")
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout.setContentsMargins(9, 0, 9, 9)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.emailFrame_5 = QtWidgets.QFrame(self.widget_30)
        self.emailFrame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_5.setObjectName("emailFrame_5")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.emailFrame_5)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_12 = QtWidgets.QLabel(self.emailFrame_5)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_37.addWidget(self.label_12)
        self.textEdit_10 = QtWidgets.QTextEdit(self.emailFrame_5)
        self.textEdit_10.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_10.setObjectName("textEdit_10")
        self.verticalLayout_37.addWidget(self.textEdit_10)
        self.verticalLayout.addWidget(self.emailFrame_5)
        self.nameFrame_3 = QtWidgets.QFrame(self.widget_30)
        self.nameFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrame_3.setObjectName("nameFrame_3")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout(self.nameFrame_3)
        self.verticalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_47.setSpacing(0)
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_13 = QtWidgets.QLabel(self.nameFrame_3)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_47.addWidget(self.label_13)
        self.textEdit_11 = QtWidgets.QTextEdit(self.nameFrame_3)
        self.textEdit_11.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_11.setObjectName("textEdit_11")
        self.verticalLayout_47.addWidget(self.textEdit_11)
        self.verticalLayout.addWidget(self.nameFrame_3)
        self.phoneNumberFrame_3 = QtWidgets.QFrame(self.widget_30)
        self.phoneNumberFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phoneNumberFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phoneNumberFrame_3.setObjectName("phoneNumberFrame_3")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.phoneNumberFrame_3)
        self.verticalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_48.setSpacing(0)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.phoneNumberLabel_3 = QtWidgets.QLabel(self.phoneNumberFrame_3)
        self.phoneNumberLabel_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.phoneNumberLabel_3.setObjectName("phoneNumberLabel_3")
        self.verticalLayout_48.addWidget(self.phoneNumberLabel_3)
        self.textEdit_12 = QtWidgets.QTextEdit(self.phoneNumberFrame_3)
        self.textEdit_12.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_12.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_12.setObjectName("textEdit_12")
        self.verticalLayout_48.addWidget(self.textEdit_12)
        self.verticalLayout.addWidget(self.phoneNumberFrame_3)
        self.emailFrame_6 = QtWidgets.QFrame(self.widget_30)
        self.emailFrame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_6.setObjectName("emailFrame_6")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.emailFrame_6)
        self.verticalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_49.setSpacing(0)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.emailLabel_3 = QtWidgets.QLabel(self.emailFrame_6)
        self.emailLabel_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.emailLabel_3.setObjectName("emailLabel_3")
        self.verticalLayout_49.addWidget(self.emailLabel_3)
        self.textEdit_13 = QtWidgets.QTextEdit(self.emailFrame_6)
        self.textEdit_13.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_13.setObjectName("textEdit_13")
        self.verticalLayout_49.addWidget(self.textEdit_13)
        self.verticalLayout.addWidget(self.emailFrame_6)
        self.emailFrame_7 = QtWidgets.QFrame(self.widget_30)
        self.emailFrame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_7.setObjectName("emailFrame_7")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.emailFrame_7)
        self.verticalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_50.setSpacing(0)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.label_14 = QtWidgets.QLabel(self.emailFrame_7)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_50.addWidget(self.label_14)
        self.textEdit_14 = QtWidgets.QTextEdit(self.emailFrame_7)
        self.textEdit_14.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_14.setObjectName("textEdit_14")
        self.verticalLayout_50.addWidget(self.textEdit_14)
        self.verticalLayout.addWidget(self.emailFrame_7)
        self.emailFrame_8 = QtWidgets.QFrame(self.widget_30)
        self.emailFrame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_8.setObjectName("emailFrame_8")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.emailFrame_8)
        self.verticalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_51.setSpacing(0)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_15 = QtWidgets.QLabel(self.emailFrame_8)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_51.addWidget(self.label_15)
        self.textEdit_15 = QtWidgets.QTextEdit(self.emailFrame_8)
        self.textEdit_15.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_15.setObjectName("textEdit_15")
        self.verticalLayout_51.addWidget(self.textEdit_15)
        self.verticalLayout.addWidget(self.emailFrame_8)
        self.verticalLayout_35.addWidget(self.widget_30, 0, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_35.addItem(spacerItem3)
        self.verticalLayout_46.addWidget(self.frame_19)
        self.horizontalLayout_20.addWidget(self.widget_15)
        self.horizontalLayout_10.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.ConfiPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setStyleSheet("")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setStyleSheet("")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_28 = QtWidgets.QFrame(self.widget_10)
        self.frame_28.setStyleSheet("")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_16 = QtWidgets.QLabel(self.frame_28)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_34.addWidget(self.label_16)
        self.verticalLayout_10.addWidget(self.frame_28, 0, QtCore.Qt.AlignHCenter)
        self.frame_20 = QtWidgets.QFrame(self.widget_10)
        self.frame_20.setStyleSheet("background-color: rgb(203, 218, 216);\n"
"border-radius: 10px;")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_19.setText("")
        self.pushButton_19.setIcon(icon)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_39.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_20.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/basic/icons/feather/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon21)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_39.addWidget(self.pushButton_20)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_39.addItem(spacerItem4)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_22)
        self.pushButton_21.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_39.addWidget(self.pushButton_21)
        self.horizontalLayout_26.addWidget(self.frame_22, 0, QtCore.Qt.AlignLeft)
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_18 = QtWidgets.QLabel(self.frame_21)
        self.label_18.setMaximumSize(QtCore.QSize(167, 167))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/icons/icons/SimboloPcDrones.svg"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_40.addWidget(self.label_18)
        self.horizontalLayout_26.addWidget(self.frame_21)
        self.verticalLayout_10.addWidget(self.frame_20)
        self.frame_27 = QtWidgets.QFrame(self.widget_10)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_18.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_23.addWidget(self.pushButton_18)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_27)
        self.pushButton_17.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pushButton_17.setStyleSheet("background-color: rgb(111, 110, 110);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_23.addWidget(self.pushButton_17)
        self.verticalLayout_10.addWidget(self.frame_27)
        self.verticalLayout_5.addWidget(self.widget_10)
        self.horizontalLayout_10.addWidget(self.widget_7)
        self.switchPagesStacked.addWidget(self.ConfiPage)
        self.missionPage = QtWidgets.QWidget()
        self.missionPage.setObjectName("missionPage")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.missionPage)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_11 = QtWidgets.QWidget(self.missionPage)
        self.widget_11.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_151 = QtWidgets.QWidget(self.widget_11)
        self.widget_151.setStyleSheet("background-color: rgb(3, 33, 77);")
        self.widget_151.setObjectName("widget_151")
        self.verticalLayout_11.addWidget(self.widget_151)
        self.widget_16 = QtWidgets.QWidget(self.widget_11)
        self.widget_16.setStyleSheet("background-color: rgb(3, 33, 77);")
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_11.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.widget_11)
        self.widget_17.setStyleSheet("background-color: rgb(3, 33, 77);")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_11.addWidget(self.widget_17)
        self.horizontalLayout_11.addWidget(self.widget_11)
        self.widget_14 = QtWidgets.QWidget(self.missionPage)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11.addWidget(self.widget_14)
        self.switchPagesStacked.addWidget(self.missionPage)
        self.reportPage = QtWidgets.QWidget()
        self.reportPage.setObjectName("reportPage")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.reportPage)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_18 = QtWidgets.QWidget(self.reportPage)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_20 = QtWidgets.QWidget(self.widget_18)
        self.widget_20.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_12.addWidget(self.widget_20)
        self.widget_21 = QtWidgets.QWidget(self.widget_18)
        self.widget_21.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_12.addWidget(self.widget_21)
        self.horizontalLayout_12.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.reportPage)
        self.widget_19.setStyleSheet("background-color: rgb(203, 218, 216);")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_12.addWidget(self.widget_19)
        self.switchPagesStacked.addWidget(self.reportPage)
        self.horizontalLayout_5.addWidget(self.switchPagesStacked)
        self.verticalLayout_4.addWidget(self.mainBodySubContainer)
        self.verticalLayout_3.addWidget(self.mainBodyContainer)
        self.verticalLayout_26.addWidget(self.mainSubWindow)
        self.stackedWidget.addWidget(self.mainWindowWidget)
        self.signInWindowWidget = QtWidgets.QWidget()
        self.signInWindowWidget.setStyleSheet("")
        self.signInWindowWidget.setObjectName("signInWindowWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.signInWindowWidget)
        self.verticalLayout_6.setContentsMargins(25, 15, 25, 25)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.signInWindowWidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/icons/MasterDrones.svg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_6.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.signInWindowWidget)
        self.widget_2.setStyleSheet("background-color: rgb(3, 33, 77);\n"
"border-radius: 30px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget_3.setStyleSheet("")
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.logInPage = QtWidgets.QWidget()
        self.logInPage.setStyleSheet("")
        self.logInPage.setObjectName("logInPage")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.logInPage)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.widget_5 = QtWidgets.QWidget(self.logInPage)
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.widget_12 = QtWidgets.QWidget(self.widget_5)
        self.widget_12.setMinimumSize(QtCore.QSize(230, 0))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_12.setAutoFillBackground(False)
        self.widget_12.setStyleSheet("background-color: transparent;")
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_19 = QtWidgets.QLabel(self.widget_12)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/icons/icons/Univalle.svg"))
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_27.addWidget(self.label_19, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_25.addWidget(self.widget_12)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setAutoFillBackground(False)
        self.widget_8.setStyleSheet("background-color: transparent;")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_7 = QtWidgets.QFrame(self.widget_8)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_45.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_45.setSpacing(0)
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.frame_24 = QtWidgets.QFrame(self.frame_7)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_8 = QtWidgets.QLabel(self.frame_24)
        self.label_8.setEnabled(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_44.addWidget(self.label_8, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_45.addWidget(self.frame_24, 0, QtCore.Qt.AlignLeft)
        self.widget_25 = QtWidgets.QWidget(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_25.sizePolicy().hasHeightForWidth())
        self.widget_25.setSizePolicy(sizePolicy)
        self.widget_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_25.setStyleSheet("background-color: rgb(203, 218, 216);\n"
"padding: 3px 3px;\n"
"border-radius: 10px;")
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_4 = QtWidgets.QLabel(self.widget_25)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_36.addWidget(self.label_4)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_25)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 32))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_36.addWidget(self.textEdit_2)
        self.frame_25 = QtWidgets.QFrame(self.widget_25)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_15.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_4.setStyleSheet("background-color: rgb(111, 110, 110);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_15.addWidget(self.pushButton_4)
        self.verticalLayout_36.addWidget(self.frame_25)
        self.verticalLayout_45.addWidget(self.widget_25)
        self.verticalLayout_19.addWidget(self.frame_7, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_25.addWidget(self.widget_8)
        self.widget_29 = QtWidgets.QWidget(self.widget_5)
        self.widget_29.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_29.setStyleSheet("background-color: transparent;")
        self.widget_29.setObjectName("widget_29")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_29)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.widget_29)
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/icons/icons/PSI.svg"))
        self.label_20.setScaledContents(False)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.label_20, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_25.addWidget(self.widget_29)
        self.widget_12.raise_()
        self.widget_29.raise_()
        self.widget_8.raise_()
        self.horizontalLayout_24.addWidget(self.widget_5)
        self.stackedWidget_3.addWidget(self.logInPage)
        self.signUpPage = QtWidgets.QWidget()
        self.signUpPage.setObjectName("signUpPage")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.signUpPage)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.widget_4 = QtWidgets.QWidget(self.signUpPage)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.widget_27 = QtWidgets.QWidget(self.widget_4)
        self.widget_27.setMinimumSize(QtCore.QSize(230, 0))
        self.widget_27.setStyleSheet("background-color: transparent;")
        self.widget_27.setObjectName("widget_27")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_27)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.widget_27)
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/icons/icons/Univalle.svg"))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_9.addWidget(self.label_23)
        self.horizontalLayout_32.addWidget(self.widget_27, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setStyleSheet("background-color: transparent;")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_4 = QtWidgets.QFrame(self.widget_9)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setSpacing(0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.frame_23 = QtWidgets.QFrame(self.frame_4)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.frame_23)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_43.addWidget(self.frame_23, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_23 = QtWidgets.QWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setMaximumSize(QtCore.QSize(500, 1000))
        self.widget_23.setStyleSheet("background-color: rgb(203, 218, 216);\n"
"padding: 3px 3px;\n"
"border-radius: 10px;")
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_24.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.emailFrame = QtWidgets.QFrame(self.widget_23)
        self.emailFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame.setObjectName("emailFrame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.emailFrame)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_5 = QtWidgets.QLabel(self.emailFrame)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_21.addWidget(self.label_5)
        self.textEdit_3 = QtWidgets.QTextEdit(self.emailFrame)
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_21.addWidget(self.textEdit_3)
        self.verticalLayout_24.addWidget(self.emailFrame)
        self.nameFrame = QtWidgets.QFrame(self.widget_23)
        self.nameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrame.setObjectName("nameFrame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.nameFrame)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_9 = QtWidgets.QLabel(self.nameFrame)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_23.addWidget(self.label_9)
        self.textEdit_5 = QtWidgets.QTextEdit(self.nameFrame)
        self.textEdit_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.verticalLayout_23.addWidget(self.textEdit_5)
        self.verticalLayout_24.addWidget(self.nameFrame)
        self.phoneNumberFrame = QtWidgets.QFrame(self.widget_23)
        self.phoneNumberFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phoneNumberFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phoneNumberFrame.setObjectName("phoneNumberFrame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.phoneNumberFrame)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.phoneNumberLabel = QtWidgets.QLabel(self.phoneNumberFrame)
        self.phoneNumberLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.verticalLayout_22.addWidget(self.phoneNumberLabel)
        self.textEdit_4 = QtWidgets.QTextEdit(self.phoneNumberFrame)
        self.textEdit_4.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_22.addWidget(self.textEdit_4)
        self.verticalLayout_24.addWidget(self.phoneNumberFrame)
        self.emailFrame_2 = QtWidgets.QFrame(self.widget_23)
        self.emailFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_2.setObjectName("emailFrame_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.emailFrame_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.emailLabel = QtWidgets.QLabel(self.emailFrame_2)
        self.emailLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout_17.addWidget(self.emailLabel)
        self.textEdit = QtWidgets.QTextEdit(self.emailFrame_2)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_17.addWidget(self.textEdit)
        self.verticalLayout_24.addWidget(self.emailFrame_2)
        self.frame_6 = QtWidgets.QFrame(self.widget_23)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_13.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_13.addWidget(self.pushButton_2)
        self.verticalLayout_24.addWidget(self.frame_6)
        self.verticalLayout_18.addWidget(self.widget_23)
        self.verticalLayout_43.addWidget(self.frame_5)
        self.verticalLayout_14.addWidget(self.frame_4)
        self.horizontalLayout_32.addWidget(self.widget_9, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.widget_28 = QtWidgets.QWidget(self.widget_4)
        self.widget_28.setStyleSheet("background-color: transparent;")
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_24 = QtWidgets.QLabel(self.widget_28)
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/icons/icons/PSI.svg"))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_42.addWidget(self.label_24)
        self.horizontalLayout_32.addWidget(self.widget_28, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_29.addWidget(self.widget_4)
        self.stackedWidget_3.addWidget(self.signUpPage)
        self.userConfiPage = QtWidgets.QWidget()
        self.userConfiPage.setObjectName("userConfiPage")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.userConfiPage)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.widget_3 = QtWidgets.QWidget(self.userConfiPage)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.widget_22 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setMinimumSize(QtCore.QSize(230, 0))
        self.widget_22.setStyleSheet("background-color: transparent;")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_22 = QtWidgets.QLabel(self.widget_22)
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/icons/icons/Univalle.svg"))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_15.addWidget(self.label_22, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.horizontalLayout_33.addWidget(self.widget_22, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.widget_24 = QtWidgets.QWidget(self.widget_3)
        self.widget_24.setStyleSheet("background-color: transparent;")
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_9 = QtWidgets.QFrame(self.widget_24)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_17.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_20.addWidget(self.frame_11, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.widget_26 = QtWidgets.QWidget(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_26.sizePolicy().hasHeightForWidth())
        self.widget_26.setSizePolicy(sizePolicy)
        self.widget_26.setMaximumSize(QtCore.QSize(500, 1000))
        self.widget_26.setStyleSheet("background-color: rgb(203, 218, 216);\n"
"padding: 3px 3px;\n"
"border-radius: 10px;")
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_27.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.emailFrame_3 = QtWidgets.QFrame(self.widget_26)
        self.emailFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_3.setObjectName("emailFrame_3")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.emailFrame_3)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_6 = QtWidgets.QLabel(self.emailFrame_3)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_28.addWidget(self.label_6)
        self.textEdit_6 = QtWidgets.QTextEdit(self.emailFrame_3)
        self.textEdit_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.verticalLayout_28.addWidget(self.textEdit_6)
        self.verticalLayout_27.addWidget(self.emailFrame_3)
        self.nameFrame_2 = QtWidgets.QFrame(self.widget_26)
        self.nameFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nameFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nameFrame_2.setObjectName("nameFrame_2")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.nameFrame_2)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_10 = QtWidgets.QLabel(self.nameFrame_2)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_29.addWidget(self.label_10)
        self.textEdit_7 = QtWidgets.QTextEdit(self.nameFrame_2)
        self.textEdit_7.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_7.setObjectName("textEdit_7")
        self.verticalLayout_29.addWidget(self.textEdit_7)
        self.verticalLayout_27.addWidget(self.nameFrame_2)
        self.phoneNumberFrame_2 = QtWidgets.QFrame(self.widget_26)
        self.phoneNumberFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phoneNumberFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phoneNumberFrame_2.setObjectName("phoneNumberFrame_2")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.phoneNumberFrame_2)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.phoneNumberLabel_2 = QtWidgets.QLabel(self.phoneNumberFrame_2)
        self.phoneNumberLabel_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.phoneNumberLabel_2.setObjectName("phoneNumberLabel_2")
        self.verticalLayout_30.addWidget(self.phoneNumberLabel_2)
        self.textEdit_8 = QtWidgets.QTextEdit(self.phoneNumberFrame_2)
        self.textEdit_8.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_8.setObjectName("textEdit_8")
        self.verticalLayout_30.addWidget(self.textEdit_8)
        self.verticalLayout_27.addWidget(self.phoneNumberFrame_2)
        self.emailFrame_4 = QtWidgets.QFrame(self.widget_26)
        self.emailFrame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emailFrame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emailFrame_4.setObjectName("emailFrame_4")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.emailFrame_4)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.emailLabel_2 = QtWidgets.QLabel(self.emailFrame_4)
        self.emailLabel_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.emailLabel_2.setObjectName("emailLabel_2")
        self.verticalLayout_31.addWidget(self.emailLabel_2)
        self.textEdit_9 = QtWidgets.QTextEdit(self.emailFrame_4)
        self.textEdit_9.setMaximumSize(QtCore.QSize(16777215, 32))
        self.textEdit_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(238, 238, 236);")
        self.textEdit_9.setObjectName("textEdit_9")
        self.verticalLayout_31.addWidget(self.textEdit_9)
        self.verticalLayout_27.addWidget(self.emailFrame_4)
        self.frame_10 = QtWidgets.QFrame(self.widget_26)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_5.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_16.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_6.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_16.addWidget(self.pushButton_6)
        self.verticalLayout_27.addWidget(self.frame_10)
        self.verticalLayout_20.addWidget(self.widget_26)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.horizontalLayout_33.addWidget(self.widget_24, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.widget_31 = QtWidgets.QWidget(self.widget_3)
        self.widget_31.setStyleSheet("background-color: transparent;")
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_21 = QtWidgets.QLabel(self.widget_31)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/icons/icons/PSI.svg"))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_41.addWidget(self.label_21)
        self.horizontalLayout_33.addWidget(self.widget_31, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.horizontalLayout_28.addWidget(self.widget_3)
        self.stackedWidget_3.addWidget(self.userConfiPage)
        self.verticalLayout_7.addWidget(self.stackedWidget_3)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.stackedWidget.addWidget(self.signInWindowWidget)
        self.horizontalLayout_30.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.switchPagesStacked.setCurrentIndex(1)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setToolTip(_translate("MainWindow", "Home"))
        self.settingsBtn.setToolTip(_translate("MainWindow", "Configuration"))
        self.missionBtn.setToolTip(_translate("MainWindow", "Mission"))
        self.reportBtn.setToolTip(_translate("MainWindow", "Report"))
        self.userBtn_2.setToolTip(_translate("MainWindow", "User "))
        self.label.setText(_translate("MainWindow", "ESTADO DRONES"))
        self.pushButton_9.setText(_translate("MainWindow", "Drone 1"))
        self.pushButton_10.setText(_translate("MainWindow", "Armado"))
        self.pushButton_33.setText(_translate("MainWindow", "Drone 2"))
        self.pushButton_34.setText(_translate("MainWindow", "Armado"))
        self.pushButton_41.setText(_translate("MainWindow", "Drone 2"))
        self.pushButton_42.setText(_translate("MainWindow", "Armado"))
        self.label_11.setText(_translate("MainWindow", "DATOS DE LA MISIÓN"))
        self.label_12.setText(_translate("MainWindow", "Nombre de la misión"))
        self.label_13.setText(_translate("MainWindow", "Nombre de la región de interes"))
        self.phoneNumberLabel_3.setText(_translate("MainWindow", "Descripción"))
        self.emailLabel_3.setText(_translate("MainWindow", "Ciudad"))
        self.label_14.setText(_translate("MainWindow", "Altura máxima"))
        self.label_15.setText(_translate("MainWindow", "Sobrelapamiento"))
        self.label_16.setText(_translate("MainWindow", "DATOS DE LA MISIÓN"))
        self.pushButton_21.setText(_translate("MainWindow", "INSERTAR"))
        self.pushButton_18.setText(_translate("MainWindow", "GENERAR TRAYECTORIA"))
        self.pushButton_17.setText(_translate("MainWindow", "INICIAR TRAYECTORIA"))
        self.label_8.setText(_translate("MainWindow", "INICIO DE SESIÓN"))
        self.label_4.setText(_translate("MainWindow", "Nombre de usuario:"))
        self.pushButton_3.setText(_translate("MainWindow", "INGRESAR"))
        self.pushButton_4.setText(_translate("MainWindow", "CREAR USUARIO"))
        self.label_2.setText(_translate("MainWindow", "REGISTRO DE USUARIO"))
        self.label_5.setText(_translate("MainWindow", "Nombre de usuario:"))
        self.label_9.setText(_translate("MainWindow", "Nombre:"))
        self.phoneNumberLabel.setText(_translate("MainWindow", "Celular:"))
        self.emailLabel.setText(_translate("MainWindow", "Correo:"))
        self.pushButton.setText(_translate("MainWindow", "REGISTRAR"))
        self.pushButton_2.setText(_translate("MainWindow", "CANCELAR"))
        self.label_3.setText(_translate("MainWindow", "CONFIGURACIÓN DE USUARIO"))
        self.label_6.setText(_translate("MainWindow", "Nombre de usuario:"))
        self.label_10.setText(_translate("MainWindow", "Nombre:"))
        self.phoneNumberLabel_2.setText(_translate("MainWindow", "Celular:"))
        self.emailLabel_2.setText(_translate("MainWindow", "Correo:"))
        self.pushButton_5.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.pushButton_6.setText(_translate("MainWindow", "CANCELAR"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

